import type { Locale } from "./i18n";

const en = {
  brand: "SheetProof", hero: ["Review XLSX changes in Git—", "then apply only", "what you approve."], description: "Compare worktree .xlsx files with local Git revisions. Align records by key, apply selected changes, undo edits, and save safely—without switching branches or committing automatically.", download: "Download SheetProof", guide: "Read the guide", truthLabel: "Product boundaries", truth: ["Files stay local", "Excel not required", "MIT licensed"],
  proof: [["Worktree file", "Includes uncommitted changes"], ["Git revision", "Read-only; no branch switch"], ["Key alignment", "Recognizes actual record changes"], ["Safe saving", "Undoable; never auto-commits"]],
  core: ["Core capabilities", "Built for XLSX configuration files in Git", "Open revisions, align records, apply approved changes, and save without leaving the review."],
  differentiators: [["Git revisions", "Compare the real worktree with a Git revision", "The left side reads the worktree, including uncommitted edits. The right side reads a validated revision without checkout, fetch, or branch switching."], ["Record alignment", "Recognize additions and deletions by key", "Detect a key column automatically or choose one from a column header. Insertions and deletions no longer turn later matching records into a wall of modifications."], ["Apply and save", "Write only approved content to the left", "Copy individual cells or whole rows into the only editable side. Every operation is undoable, and saving checks for external changes before atomic replacement."]], more: "See every feature and limitation",
  compareHeading: ["Comparison model", "Compare records, not just row numbers", "SheetProof reads the worktree and Git revision directly, then writes approved results to the left file."], compareLabel: "Comparison of common spreadsheet review workflows", compare: [["Review stage", "Coordinate-based or manual", "SheetProof"], ["Version source", "Prepare two file copies manually", "Compare the worktree directly with a validated Git revision"], ["Record changes", "A1, A2… coordinates can shift every later record", "Reliable records align by key; ambiguous records fall back to physical rows"], ["Applied result", "Return to the original file and reproduce changes", "Write cells or rows to the left with undo history"], ["Git operations", "Manage branch and worktree state separately", "No branch switch, fetch, add, or commit"]],
  processHeading: ["Compare and apply", "Review in four steps"], process: [["Open sources", "Choose two .xlsx files, or open a local Git repository and select an existing revision."], ["Inspect differences", "Navigate added, deleted, modified, and conflict data in synchronized panes."], ["Apply changes", "Copy approved cells or rows to the left; every operation enters undo history."], ["Save safely", "Detect external changes, verify a temporary file, then atomically replace the worktree file."]],
  casesHeading: ["Use cases", "Common workflows"], cases: [["Review configuration changes", "Check values, formulas, types, and whole-row changes before a commit or release."], ["Review XLSX changes in Git", "Compare the worktree with local or remote-tracking revisions without interrupting the current branch."], ["Apply selected corrections", "Accept only approved cells or rows, with undo available until saving."]],
  trust: [["Local processing", "Workbooks are never uploaded; the website has no workbook upload endpoint."], ["Open and verifiable", "MIT licensed, with SHA-256 checksum files for release assets."], ["Bounded saving", "Only the left side is writable; external changes are checked before atomic replacement."]],
  ugit: ["UGit integration", "Use SheetProof from UGit", "Register SheetProof as UGit's .xlsx diff and merge tool. The worktree stays editable on the left and snapshots stay read-only; saving remains an explicit action.", "Setup and usage"], boundary: ["Current scope", "Currently supports .xlsx", "SheetProof handles comparison, approved changes, and safe saving. Keep using your existing tools for modeling, formatting, and Git commits.", "See supported scope"], cta: ["Version", "Download SheetProof", "Windows and macOS previews are available from GitHub Releases with SHA-256 checksums.", "Go to downloads"],
} as const;

const zhCN = {
  brand: "SheetProof · 表鉴", hero: ["审阅 Git 中的 XLSX，", "只应用", "确认过的修改。"], description: "直接比较工作区中的 .xlsx 与本地 Git 版本。支持按主键对齐记录、逐项应用、撤销和安全保存；不切换分支，也不自动提交。", download: "下载 SheetProof", guide: "查看使用说明", truthLabel: "产品边界", truth: ["文件不上传", "无需 Excel", "MIT 开源"],
  proof: [["工作区文件", "包含尚未提交的修改"], ["Git 版本", "右侧只读，不切换分支"], ["主键对齐", "识别实际记录增删"], ["安全保存", "可撤销，不自动提交"]], core: ["核心能力", "针对 Git 管理的 XLSX 配置表", "从读取版本、对齐记录到应用修改和保存，均围绕配置表审阅设计。"], differentiators: [["Git 版本", "直接比较工作区与 Git 版本", "左侧读取尚未提交的工作区文件，右侧读取已验证的 Git 版本；不 checkout、不 fetch，也不切换分支。"], ["记录对齐", "按主键识别新增与删除", "自动识别或右键指定主键列。中间新增、删除不再把后续共同记录放大成连续修改。"], ["应用与保存", "只将确认内容写入左侧", "逐格或整行写入唯一可编辑的左侧，所有操作可撤销；保存前检测外部修改并执行原子替换。"]], more: "查看全部功能与限制",
  compareHeading: ["对比方式", "按记录比较，而不是只按行号", "SheetProof 直接读取工作区和 Git 版本，并将确认结果写回左侧文件。"], compareLabel: "常见表格对比流程与 SheetProof 的区别", compare: [["审阅环节", "坐标式或手工流程", "SheetProof"], ["版本来源", "手动准备两个文件副本", "工作区直接比较已验证的 Git 版本"], ["记录增删", "按 A1、A2…比较，后续记录可能错位", "可靠记录按主键对齐，歧义记录回退物理行"], ["应用结果", "查看后回到原文件手动整理", "逐格或整行写入左侧，并进入撤销历史"], ["Git 操作", "另外维护当前分支和工作区状态", "不切分支、不 fetch、不自动 add 或 commit"]], processHeading: ["比较与应用", "四个步骤完成审阅"], process: [["打开来源", "选择两个 .xlsx，或打开本地 Git 仓库并选择已有版本。"], ["检查差异", "在同步双栏中按分类导航，查看值、公式、类型和行状态。"], ["应用修改", "把确认过的单元格或整行应用到左侧；所有操作进入撤销历史。"], ["安全保存", "检测外部修改，校验临时文件，再原子替换工作区文件。"]], casesHeading: ["适用场景", "常见使用场景"], cases: [["审阅配置表变更", "在提交或发版前核对数值、公式、类型和整行变化。"], ["处理 Git 中的 XLSX 变化", "比较工作区与本地分支或远端跟踪版本，不打断当前分支上的工作。"], ["选择性应用修改", "只接收确认过的单元格或整行，保存前仍可撤销。"]], trust: [["本地处理", "工作簿不上传，官网也没有文件上传入口。"], ["开源可核验", "MIT License，发布资产提供 SHA-256 校验文件。"], ["保存有边界", "左侧唯一可写；检测外部修改后再原子替换。"]], ugit: ["UGit 集成", "在 UGit 中调用 SheetProof", "SheetProof 可注册为 UGit 的 .xlsx 差异与合并工具。工作区文件保持在可编辑左侧，版本快照只读；保存仍由你明确触发。", "查看接入与使用方式"], boundary: ["当前范围", "当前支持 .xlsx", "SheetProof 负责比较、应用确认内容与安全保存；表格建模、格式设计和 Git 提交仍交给你熟悉的工具。", "查看支持范围"], cta: ["版本", "下载 SheetProof", "Windows 与 macOS 预览版由 GitHub Releases 提供，并附带 SHA-256 校验文件。", "前往下载"],
};

const ja = {
  brand: "SheetProof（シートプルーフ）", hero: ["Git 上の XLSX 変更を確認。", "必要な項目だけを", "左側へ反映。"], description: "ワークツリーの .xlsx をローカルの Git リビジョンと直接比較します。キーによるレコード照合、選択的な反映、元に戻す操作、安全な保存に対応。ブランチの切り替えや自動コミットは行いません。", download: "SheetProof をダウンロード", guide: "使い方を見る", truthLabel: "製品の境界", truth: ["ファイルはローカルのまま", "Excel 不要", "MIT ライセンス"],
  proof: [["ワークツリーファイル", "未コミットの変更を含む"], ["Git リビジョン", "右側は読み取り専用、ブランチ切替なし"], ["キーで比較", "実際のレコード追加・削除を識別"], ["安全な保存", "取り消し可能、自動コミットなし"]], core: ["主な機能", "Git で管理する XLSX 設定表のために", "リビジョンの読み込み、レコード照合、変更の反映、安全な保存までを一つの画面で行えます。"], differentiators: [["Git リビジョン", "実際のワークツリーと Git リビジョンを比較", "左側は未コミットの変更を含むワークツリー、右側は検証済みの Git リビジョンです。checkout、fetch、ブランチ切り替えは行いません。"], ["レコード照合", "キーで追加と削除を識別", "キー列を自動検出するか、列見出しから指定できます。途中の追加・削除で後続レコード全体が変更扱いになるのを防ぎます。"], ["反映と保存", "確認した内容だけを左側へ反映", "セル単位または行単位で、唯一編集できる左側へ反映します。すべて取り消し可能で、保存前に外部変更を確認してアトミック置換します。"]], more: "機能と制限をすべて見る",
  compareHeading: ["比較方法", "行番号だけでなく、レコードとして比較", "SheetProof はワークツリーと Git リビジョンを直接読み込み、確認した結果を左側のファイルへ反映します。"], compareLabel: "一般的な表計算レビュー手順と SheetProof の比較", compare: [["確認工程", "座標ベースまたは手作業", "SheetProof"], ["バージョン元", "2 つのファイルコピーを手動で準備", "ワークツリーと検証済みの Git リビジョンを直接比較"], ["レコード変更", "A1、A2…で比較すると後続レコードがずれる", "信頼できるレコードはキーで揃え、曖昧なものだけ物理行で比較"], ["反映結果", "元ファイルへ戻って手動で反映", "セルまたは行を左側へ反映し、取り消し履歴に記録"], ["Git 操作", "ブランチとワークツリーの状態を別途管理", "ブランチ切替、fetch、add、commit は行わない"]], processHeading: ["比較と反映", "4 ステップでレビュー"], process: [["比較元を開く", "2 つの .xlsx を選ぶか、ローカル Git リポジトリを開いてリビジョンを選択します。"], ["差分を確認", "同期した 2 ペインで分類ごとに移動し、値、数式、型、行状態を確認します。"], ["変更を反映", "確認したセルまたは行を左側へ反映します。すべて取り消し履歴に残ります。"], ["安全に保存", "外部変更を検出し、一時ファイルを検証してからワークツリーファイルをアトミック置換します。"]], casesHeading: ["利用例", "よくあるワークフロー"], cases: [["設定表の変更レビュー", "コミットやリリース前に、値、数式、型、行全体の変更を確認します。"], ["Git 上の XLSX 変更を確認", "現在のブランチを中断せず、ワークツリーとローカル／リモート追跡リビジョンを比較します。"], ["修正を選んで反映", "確認したセルまたは行だけを反映し、保存までは取り消せます。"]], trust: [["ローカル処理", "ブックはアップロードされず、Web サイトにもアップロード機能はありません。"], ["検証できるオープンソース", "MIT ライセンス。リリース資産には SHA-256 チェックサムを用意しています。"], ["保存範囲を限定", "書き込めるのは左側だけ。外部変更を確認してからアトミック置換します。"]], ugit: ["UGit 連携", "UGit から SheetProof を使用", "SheetProof を UGit の .xlsx 差分・マージツールとして登録できます。ワークツリーは左側で編集可能、スナップショットは読み取り専用です。保存は明示的に実行します。", "設定と使い方を見る"], boundary: ["現在の対応範囲", "現在は .xlsx に対応", "SheetProof は比較、確認した変更の反映、安全な保存を担当します。表設計、書式、Git コミットには使い慣れたツールを引き続き利用してください。", "対応範囲を見る"], cta: ["バージョン", "SheetProof をダウンロード", "Windows／macOS プレビューを GitHub Releases から入手できます。SHA-256 チェックサム付きです。", "ダウンロードへ"],
};

export const homeCopy = { en, "zh-CN": zhCN, ja } satisfies Record<Locale, object>;
