import type { Locale } from "./i18n";

const features = {
  en: {
    intro: ["Features", "Review, apply, and save XLSX changes from Git", "Compare a worktree workbook with a Git revision, align records by key, and write approved results to the left."],
    scope: ["Compared content", "Values · formulas · types · worksheets", "Formatting is not part of equality."],
    stories: [
      ["Git revisions", "Compare the real worktree with a local Git revision", "Repository mode reads the uncommitted worktree file on the left and a validated Git revision on the right. It never checks out, fetches, or switches branches.", "Worktree remains editable", "Git snapshot remains read-only", "Saving never runs add or commit"],
      ["Record alignment", "Match the same record by key", "When a reliable key exists on both sides, SheetProof aligns shared records and keeps one-sided records near their original neighbors. Without a reliable key, it compares physical rows.", "Detects id or one unique *ID header", "A column header menu can set the key", "Ambiguous records alone use physical rows"],
      ["Apply and save", "Write approved results to the left", "Apply selected cells or rows to the left. Edits, overwrites, and appends enter undo history. Before saving, SheetProof checks for external changes and validates a temporary file.", "Only the left side is writable", "Cell and row operations are undoable", "Reopen validation and atomic replacement"],
    ],
    supporting: ["Review tools", "Navigate large workbooks and find changes", "Synchronized scrolling, row filters, before/after preview, and guarded saving keep the review focused."],
    compare: ["Screenshots", "See the same data under both comparison modes", "Every screenshot uses the current Windows build and the same localized character workbook."],
    alignment: ["Records inserted between existing rows", "Row-position comparison shifts later records. Key comparison preserves the real additions and field changes.", "By row position · 90 differences", "By key · 16 differences"],
    merge: ["Before and after one approved change", "Only the selected HP value is applied. The remaining differences stay unchanged.", "Before · 16 differences", "After · 15 differences"],
    limitsIntro: ["Supported scope", "What SheetProof currently handles", "SheetProof focuses on common .xlsx content and local version-control workflows. The following areas are outside its current scope."],
    limits: [["File formats", "Supports .xlsx only. .xls, .xlsm, .ods, CSV, and encrypted workbooks are not supported."], ["Advanced objects", "Charts, images, pivot tables, macros, external connections, and complex conditional formatting are not edited or guaranteed to round-trip intact."], ["Git operations", "Does not fetch, pull, push, add, or commit, and does not create, delete, or switch branches."], ["Editing scope", "This is not an Excel replacement: there is no redo, formatting toolbar, full formula calculation, or whole-workbook copy."]],
  },
  "zh-CN": {
    intro: ["功能", "比较、应用并保存 Git 中的 XLSX 修改", "比较工作区与 Git 版本中的 .xlsx，按主键对齐记录，并将确认结果写入左侧。"],
    scope: ["比较内容", "值 · 公式 · 类型 · 工作表", "格式不计入内容差异。"],
    stories: [["Git 版本", "比较真实工作区与本地 Git 版本", "仓库模式在左侧读取包含未提交修改的工作区文件，在右侧读取经过校验的 Git 版本。整个过程不会 checkout、fetch 或切换分支。", "工作区保持可编辑", "Git 快照始终只读", "保存不自动 add 或 commit"], ["记录对齐", "按主键对齐同一条记录", "双方存在可靠主键时，SheetProof 会对齐共同记录，并将单侧记录保留在原有相邻位置。没有可靠主键时，才按物理行比较。", "自动识别 id 或唯一的 *ID 表头", "可从列标题菜单指定主键", "仅歧义记录回退物理行"], ["应用与保存", "将确认结果写入左侧", "把选中的单元格或整行应用到左侧。编辑、覆盖和追加都会进入撤销历史；保存前还会检测外部修改并校验临时文件。", "左侧是唯一可写来源", "逐格与整行操作均可撤销", "重开校验与原子替换"]],
    supporting: ["审阅工具", "浏览大表并快速定位差异", "同步滚动、行筛选、修改前预览和受保护的保存流程，让审阅保持聚焦。"],
    compare: ["功能截图", "用同一组数据比较两种对齐方式", "所有截图均来自当前 Windows 构建和同一份本地化角色配置表。"],
    alignment: ["在现有记录之间插入数据", "按行号比较会让后续记录错位；按主键比较只保留真实新增和字段修改。", "按行号 · 90 处差异", "按主键 · 16 处差异"],
    merge: ["应用一项修改前后", "只应用选中的生命值，其他差异保持不变。", "应用前 · 16 处差异", "应用后 · 15 处差异"],
    limitsIntro: ["支持范围", "SheetProof 当前支持什么", "SheetProof 专注常见 .xlsx 内容和本地版本管理流程。以下内容目前不在支持范围内。"],
    limits: [["文件格式", "仅支持 .xlsx；不支持 .xls、.xlsm、.ods、CSV 和加密工作簿。"], ["高级对象", "不会编辑图表、图片、透视表、宏、外部连接或复杂条件格式，也不保证这些对象完整保真。"], ["Git 操作", "不执行 fetch、pull、push、add 或 commit，也不创建、删除或切换分支。"], ["编辑范围", "SheetProof 不能替代 Excel：不提供重做、格式工具栏、完整公式计算或整表复制。"]],
  },
  ja: {
    intro: ["機能", "Git 上の XLSX を比較し、必要な変更だけを保存", "ワークツリーと Git リビジョンの .xlsx を比較し、キーでレコードを揃え、確認した内容を左側へ反映します。"],
    scope: ["比較対象", "値・数式・型・シート", "書式は内容の差分に含めません。"],
    stories: [["Git リビジョン", "実際のワークツリーとローカルの Git リビジョンを比較", "リポジトリモードでは、未コミットの変更を含むワークツリーファイルを左側に、検証済みの Git リビジョンを右側に読み込みます。checkout、fetch、ブランチ切り替えは行いません。", "ワークツリーは編集可能", "Git スナップショットは読み取り専用", "保存時に add や commit を実行しない"], ["レコード照合", "同じレコードをキーで揃える", "両側に信頼できるキーがある場合、共通レコードを揃え、片側だけのレコードは元の並びに近い位置へ残します。キーを確定できない場合は物理行で比較します。", "id または一意の *ID 見出しを検出", "列見出しのメニューからキーを指定可能", "曖昧なレコードだけ物理行にフォールバック"], ["反映と保存", "確認した結果を左側へ反映", "選択したセルまたは行を左側へ反映します。編集、上書き、追加は取り消し履歴に記録されます。保存前には外部での変更を確認し、一時ファイルを検証します。", "書き込めるのは左側だけ", "セル・行単位の操作を取り消し可能", "再オープン検証とアトミック置換"]],
    supporting: ["レビュー機能", "大きなブックでも差分をすばやく確認", "同期スクロール、行フィルター、変更前プレビュー、安全な保存手順で確認作業に集中できます。"],
    compare: ["スクリーンショット", "同じデータで 2 つの比較方法を確認", "すべて現在の Windows ビルドと、同じ内容の日本語キャラクター設定表を使用しています。"],
    alignment: ["既存レコードの間にデータを追加した場合", "行番号で比較すると後続レコードがずれます。キーで比較すれば、実際の追加と項目変更だけが残ります。", "行番号で比較・差分 90 件", "キーで比較・差分 16 件"],
    merge: ["1 件を反映する前と後", "選択した HP だけを反映し、ほかの差分は変更しません。", "反映前・差分 16 件", "反映後・差分 15 件"],
    limitsIntro: ["対応範囲", "現在対応している内容", "SheetProof は一般的な .xlsx の内容とローカルのバージョン管理作業を対象としています。次の項目は現在の対応範囲外です。"],
    limits: [["ファイル形式", ".xlsx のみ対応しています。.xls、.xlsm、.ods、CSV、暗号化されたブックは対応していません。"], ["高度なオブジェクト", "グラフ、画像、ピボットテーブル、マクロ、外部接続、複雑な条件付き書式は編集せず、完全な保持も保証しません。"], ["Git 操作", "fetch、pull、push、add、commit は実行しません。ブランチの作成、削除、切り替えも行いません。"], ["編集範囲", "Excel の代替ではありません。やり直し、書式ツールバー、完全な数式計算、ブック全体のコピーはありません。"]],
  },
} as const;

const guide = {
  en: {
    intro: ["Guide", "Review and apply changes in three steps", "Open a comparison, inspect the differences, then save only the changes you approve."],
    steps: [["Open a comparison", "Choose two .xlsx files, or open a local Git repository and select a worktree file and Git revision. The left side is editable; the right side is read-only."], ["Inspect differences", "Counts describe the current worksheet. Filter added, deleted, modified, or conflict rows, then inspect both values, types, and row status for the selected cell."], ["Apply and save", "Copy approved cells or rows to the left. Hold Before or Tab to review the original value, then save when the result is ready."]],
    shortcuts: ["Keyboard shortcuts", "Common actions", ["Filter difference rows", "1–4 categories; 5 all"], ["Select all cells", "Ctrl / ⌘ + A"], ["Clear the left selection", "Backspace / Delete"], ["Show original value", "Hold Tab while a grid is focused"], ["Save", "Ctrl / ⌘ + S"], ["Save As", "Ctrl / ⌘ + Shift + S"], ["Undo", "Ctrl / ⌘ + Z"], ["Zoom", "Ctrl / ⌘ + mouse wheel"], ["Edit left cell", "Double-click the cell"]],
    modes: [["Open files", "Two-file mode", "Use this for a one-off comparison. The left workbook is editable and can be saved elsewhere; the right workbook stays read-only."], ["Open repository", "Git repository mode", "Use this for versioned configuration workbooks. Choose or drop a local repository, then compare the real worktree on the left with a selected Git revision on the right."]],
    ugit: ["UGit integration", "Configure UGit from SheetProof", "Keep SheetProof in a permanent location, then register it once from the app.", ["Keep the app in one location", "Move the .exe or SheetProof.app to its permanent folder. If you move it later, configure UGit again."], ["Choose Configure UGit", "The confirmation dialog shows the active Git configuration source and any existing XLSX tool paths."], ["Confirm the XLSX tool replacement", "Only the diff and merge tools for *.xlsx are changed. CSV and other file types are left alone. Restart UGit afterward."], ["Compare from UGit", "The worktree opens editable on the left and the Git snapshot read-only on the right. You still choose when to stage and commit."]],
    ugitNote: ["Two XLSX diff-tool entries are expected", "UGit keeps both SpreadsheetCompare and Custom compatibility entries in its diff-tool list, plus one Custom merge-tool entry. Do not remove either diff entry."],
    faq: [["Are workbooks uploaded?", "No. This release reads and processes them locally, and the website has no workbook upload endpoint."], ["What if another app changes an open workbook?", "SheetProof detects it. A changed read-only source is reloaded; for the editable left side, SheetProof asks before discarding unsaved session edits and loading the disk version."], ["Does Save commit to Git?", "No. Save only updates the current worktree file. Staging, committing, and pushing remain in your Git tools."], ["Can it open macro-enabled workbooks?", "No. This release supports .xlsx only and rejects .xlsm before opening."]],
  },
  "zh-CN": {
    intro: ["使用说明", "三步完成差异审阅", "打开对比、核对差异，再保存确认过的修改。"],
    steps: [["打开对比", "选择左右两个 .xlsx，或打开本地 Git 仓库并选择工作区文件和 Git 版本。左侧可编辑，右侧始终只读。"], ["检查差异", "数量仅对应当前工作表。可筛选新增、删除、修改或冲突行，再核对所选单元格两侧的值、类型和行状态。"], ["应用并保存", "把确认过的单元格或整行复制到左侧。按住“修改前”或 Tab 可回看原值，结果确认后再保存。"]],
    shortcuts: ["快捷键", "常用操作", ["筛选差异行", "1–4 切换分类；5 显示全部"], ["全选单元格", "Ctrl / ⌘ + A"], ["清空左侧选区", "Backspace / Delete"], ["查看原值", "表格聚焦后按住 Tab"], ["保存", "Ctrl / ⌘ + S"], ["另存为", "Ctrl / ⌘ + Shift + S"], ["撤销", "Ctrl / ⌘ + Z"], ["缩放", "Ctrl / ⌘ + 鼠标滚轮"], ["编辑左侧单元格", "双击单元格"]],
    modes: [["打开文件", "双文件模式", "适合临时核对两个工作簿。左侧可编辑并可另存，右侧始终只读。"], ["打开仓库", "Git 仓库模式", "适合纳入版本管理的配置表。选择或拖入本地仓库后，在左侧读取真实工作区，在右侧读取所选 Git 版本。"]],
    ugit: ["UGit 集成", "从 SheetProof 配置 UGit", "将 SheetProof 放在固定位置，然后在应用中注册一次。", ["固定应用位置", "把 .exe 或 SheetProof.app 放到长期使用的目录。以后移动应用，需要重新配置 UGit。"], ["选择“配置 UGit”", "确认对话框会显示当前 Git 配置来源和已有的 XLSX 工具路径。"], ["确认替换 XLSX 工具", "只更新 *.xlsx 的差异和合并工具，不影响 CSV 或其他文件类型。完成后重启 UGit。"], ["从 UGit 发起对比", "工作区在可编辑左侧打开，Git 快照在只读右侧打开。暂存和提交仍由你决定。"]],
    ugitNote: ["出现两条 XLSX 差异工具是正常现象", "UGit 会在差异工具列表中保留 SpreadsheetCompare 和 Custom 两个兼容入口，并在合并工具中保留一个 Custom。无需删除任何一条差异工具。"],
    faq: [["工作簿会上传吗？", "不会。当前版本只在本机读取和处理，官网也没有工作簿上传入口。"], ["其他程序修改了已打开的工作簿怎么办？", "SheetProof 会检测变化。只读来源会重新载入；左侧可编辑文件发生变化时，会先询问是否放弃会话中未保存的修改，再载入磁盘版本。"], ["保存会自动提交到 Git 吗？", "不会。保存只更新当前工作区文件；暂存、提交和推送仍由现有 Git 工具完成。"], ["能打开启用宏的工作簿吗？", "不能。当前只支持 .xlsx，打开前会拒绝 .xlsm。"]],
  },
  ja: {
    intro: ["使い方", "3 ステップで差分を確認", "比較元を開き、差分を確認して、必要な変更だけを保存します。"],
    steps: [["比較元を開く", "2 つの .xlsx を選ぶか、ローカル Git リポジトリからワークツリーファイルと Git リビジョンを選択します。左側は編集可能、右側は読み取り専用です。"], ["差分を確認", "件数は現在のシートだけを表します。追加、削除、変更、競合で行を絞り込み、選択したセルの値、型、行状態を両側で確認します。"], ["反映して保存", "確認したセルまたは行を左側へ反映します。「変更前」または Tab を押して元の値を確認し、問題がなければ保存します。"]],
    shortcuts: ["ショートカット", "よく使う操作", ["差分行を絞り込む", "1～4 で分類、5 ですべて表示"], ["すべてのセルを選択", "Ctrl / ⌘ + A"], ["左側の選択範囲をクリア", "Backspace / Delete"], ["元の値を表示", "表にフォーカスして Tab を押し続ける"], ["保存", "Ctrl / ⌘ + S"], ["名前を付けて保存", "Ctrl / ⌘ + Shift + S"], ["元に戻す", "Ctrl / ⌘ + Z"], ["ズーム", "Ctrl / ⌘ + マウスホイール"], ["左側のセルを編集", "セルをダブルクリック"]],
    modes: [["ファイルを開く", "2 ファイルモード", "一時的に 2 つのブックを確認する場合に使います。左側は編集して別名で保存でき、右側は常に読み取り専用です。"], ["リポジトリを開く", "Git リポジトリモード", "バージョン管理している設定表向けです。ローカルリポジトリを選択またはドロップし、左側の実際のワークツリーと右側の Git リビジョンを比較します。"]],
    ugit: ["UGit 連携", "SheetProof から UGit を設定", "SheetProof を固定の場所に置き、アプリから一度登録します。", ["アプリの場所を固定", ".exe または SheetProof.app を今後も使うフォルダーへ移します。あとで移動した場合は再設定が必要です。"], ["「UGit 設定」を選択", "確認ダイアログに、使用中の Git 設定元と既存の XLSX ツールパスが表示されます。"], ["XLSX ツールの変更を確認", "変更するのは *.xlsx の差分・マージツールだけです。CSV などほかの形式には影響しません。完了後に UGit を再起動します。"], ["UGit から比較", "ワークツリーは編集可能な左側、Git スナップショットは読み取り専用の右側で開きます。ステージとコミットは引き続き自分で行います。"]],
    ugitNote: ["XLSX の差分ツールが 2 件表示されるのは正常です", "UGit の差分ツール一覧には、互換用の SpreadsheetCompare と Custom が残ります。マージツールは Custom 1 件です。差分ツールのどちらも削除する必要はありません。"],
    faq: [["ブックはアップロードされますか？", "いいえ。このリリースはローカルで読み込みと処理を行い、Web サイトにもアップロード機能はありません。"], ["開いているブックが別のアプリで変更された場合は？", "SheetProof が変更を検出します。読み取り専用側は再読み込みします。編集可能な左側では、未保存の変更を破棄するか確認してからディスク上の最新版を読み込みます。"], ["保存すると Git にコミットされますか？", "いいえ。保存では現在のワークツリーファイルだけを更新します。ステージ、コミット、push は普段の Git ツールで行います。"], ["マクロ有効ブックを開けますか？", "いいえ。現在は .xlsx のみ対応し、.xlsm は開く前に拒否します。"]],
  },
} as const;

const download = {
  en: { intro: ["Download", "Download SheetProof", "Windows amd64 and macOS universal preview builds are available from GitHub Releases. Verify the SHA-256 checksum after downloading."], windows: ["Standalone EXE", "Windows preview", "Run the SheetProof executable after downloading. This build is unsigned, so Windows may show a security warning the first time it runs.", "Download for Windows"], mac: ["Apple Silicon + Intel", "macOS preview", "Download the universal app archive. This build is unsigned and not notarized by Apple, so macOS requires you to explicitly allow the first launch.", "Download for macOS"], trust: ["Download and privacy", ["Files stay local", "Neither the app nor the website uploads workbooks."], ["MIT licensed", "The source and build workflow are open for review."], ["SHA-256 checksums", "Download checksums →"]], source: ["Source", "Build from source", "Requires Go 1.24+, Node.js 20+, and the desktop build tools for your platform.", "Download source"], releases: ["Versions and assets", "GitHub Releases", "See release notes, platform assets, and the complete checksum file.", "View Releases →"], build: ["Build from source", "Local build", ["Install dependencies", "Prepare Go, Node.js, and the desktop build tools for your platform."], ["Build the frontend", "Install dependencies in frontend and create the production assets."], ["Build the desktop app", "Use the repository script on Windows or the Wails build command on macOS."], ["Run the app", "The result is written to build/bin."]], note: ["Before downloading", "is a preview. The desktop builds are unsigned, and the macOS build is not notarized. Download only from this project's GitHub Releases and verify SHA-256."] },
  "zh-CN": { intro: ["下载", "下载 SheetProof", "Windows amd64 与 macOS universal 预览版由 GitHub Releases 提供。下载后请核对 SHA-256。"], windows: ["独立 EXE", "Windows 预览版", "下载后直接运行 SheetProof 可执行文件。当前构建未经签名，首次运行时 Windows 可能显示安全提示。", "下载 Windows 版"], mac: ["Apple Silicon + Intel", "macOS 预览版", "下载 universal 应用压缩包。当前构建未经签名，也未通过 Apple 公证；首次打开时需要由你明确允许。", "下载 macOS 版"], trust: ["下载与隐私", ["文件留在本机", "应用与官网都不会上传工作簿。"], ["MIT 开源", "源码和构建流程可公开核验。"], ["SHA-256 校验", "下载校验文件 →"]], source: ["源码", "从源码构建", "需要 Go 1.24+、Node.js 20+ 和对应平台的桌面构建环境。", "下载源码"], releases: ["版本与资产", "GitHub Releases", "查看更新内容、平台产物和完整校验文件。", "查看 Releases →"], build: ["从源码构建", "本地构建", ["安装依赖", "准备 Go、Node.js 和对应平台的桌面构建环境。"], ["构建前端", "在 frontend 目录安装依赖并生成生产资源。"], ["构建桌面端", "Windows 使用仓库脚本，macOS 使用 Wails 构建命令。"], ["启动应用", "构建结果位于 build/bin。"]], note: ["下载前说明", "是预览版本。桌面构建未经签名，macOS 构建也未经公证。请只从本项目的 GitHub Releases 下载并核对 SHA-256。"] },
  ja: { intro: ["ダウンロード", "SheetProof をダウンロード", "Windows amd64／macOS universal のプレビュー版を GitHub Releases から入手できます。ダウンロード後に SHA-256 を確認してください。"], windows: ["単体 EXE", "Windows プレビュー", "ダウンロードした SheetProof の実行ファイルを起動します。現在のビルドは未署名のため、初回起動時に Windows の警告が表示される場合があります。", "Windows 版をダウンロード"], mac: ["Apple Silicon + Intel", "macOS プレビュー", "universal アプリの ZIP をダウンロードします。現在のビルドは未署名かつ Apple の公証を受けていないため、初回起動時はユーザーによる許可が必要です。", "macOS 版をダウンロード"], trust: ["ダウンロードとプライバシー", ["ファイルはローカルのまま", "アプリも Web サイトもブックをアップロードしません。"], ["MIT ライセンス", "ソースコードとビルド手順を確認できます。"], ["SHA-256 チェックサム", "チェックサムをダウンロード →"]], source: ["ソースコード", "ソースからビルド", "Go 1.24 以降、Node.js 20 以降、お使いの OS 向けデスクトップビルド環境が必要です。", "ソースをダウンロード"], releases: ["バージョンと資産", "GitHub Releases", "変更内容、各 OS 向けファイル、チェックサム一覧を確認できます。", "Releases を見る →"], build: ["ソースからビルド", "ローカルビルド", ["依存関係を準備", "Go、Node.js、お使いの OS 向けデスクトップビルド環境を用意します。"], ["フロントエンドをビルド", "frontend で依存関係をインストールし、本番用アセットを生成します。"], ["デスクトップアプリをビルド", "Windows ではリポジトリ内のスクリプト、macOS では Wails のビルドコマンドを使用します。"], ["アプリを起動", "ビルド結果は build/bin に出力されます。"]], note: ["ダウンロード前の注意", "はプレビュー版です。デスクトップビルドは未署名で、macOS 版は公証も受けていません。このプロジェクトの GitHub Releases からのみ入手し、SHA-256 を確認してください。"] },
} as const;

export const pageCopy = { features, guide, download } satisfies Record<string, Record<Locale, object>>;
